[package]
name = "wasi-preset-args"
version = "0.1.0"
edition = "2021"

[dependencies]
walrus = "0.19.0"
anyhow = "1.0.0"
clap = { optional = true, version = "3.0", features = ["derive"] }

[[bin]]
name = "wasi-preset-args"
required-features = ["clap"]
